### ISSUE TITLE
Question Regarding makeApiCall

### ISSUE THREAD

**Issue by nutterb** [vubiostat/redcapAPI-vignette#1]
This vignette shows users how to customize an API call with `makeApiCall`.  While we've exposed this function to the user, we chose not to expose `vectorToApiBodyList`, as it was kind of utilitarian within the package. In an e-mail conversation, we briefly talked about changing that decision. Do we want to 

* export `vectorToApiBodyList`, or 
* leave it unexposed and highlight that it can be done with a triple colon (`redcapAPI:::vectorToApiBodyList`). 
* Not mention it at all

It's a pretty power-user kind of thing to do, so I don't have strong opinions either way.

**Comment by spgarbet** [comment]
I think I added export recently to that, it was fully documented. I was initially against it, but I've flipped to the other side when we were designing the forms call. It's too useful for properly building an API call. It probably should be part of the vignette to future proof if the core REDCap team turns on strict mode again.

I'd put it in an Appendix of the document.

**Comment by nutterb** [comment]
Oh.  so you did.  I didn't see it the first time I looked for it.
